export enum PermissionKey {
    READ_USER = "READ_USER",
    CREATE_USER = "CREATE_USER",
    UPDATE_USER = "UPDATE_USER",
    DELETE_USER = "DELETE_USER",
    READ_ROLE = "READ_ROLE",
    CREATE_ROLE = "CREATE_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",
    DELETE_ROLE = "DELETE_ROLE",
}